#!/bin/bash

# Stock Valuation App - Google Play Store Deployment Guide
# Complete step-by-step walkthrough for deploying to Google Play Store

echo "🤖 Stock Valuation App - Google Play Store Deployment"
echo "================================================================"
echo ""

# Prerequisites
echo "✅ STEP 1: Prerequisites"
echo "---"
echo "You need:"
echo "  ✓ Google Play Developer account ($25 one-time)"
echo "  ✓ Backend deployed (Render URL ready)"
echo "  ✓ Keystore file for signing (or create new)"
echo ""
read -p "Press Enter once you have Google Play Developer account..."
echo ""

# Step 2: Create Keystore (First time only)
echo "✅ STEP 2: Create Release Keystore"
echo "---"
echo "If this is your first time, create a keystore:"
echo ""
echo "  keytool -genkey -v -keystore my-release-key.jks \\"
echo "    -keyalg RSA -keysize 2048 -validity 10000 \\"
echo "    -alias my-key-alias"
echo ""
echo "You'll be prompted for:"
echo "  - Keystore password (remember this!)"
echo "  - Key password"
echo "  - Full name, company, etc."
echo ""
echo "Save this file somewhere safe:"
echo "  /Users/abiodunquadri/kivy/new\\ work\\ foler/stock-valuation-app/mobile/my-release-key.jks"
echo ""
read -p "Press Enter after creating keystore..."
echo ""

# Step 3: Configure EAS
echo "✅ STEP 3: Configure EAS for Android"
echo "---"
echo "Update app.json with Android config:"
echo ""
echo '   {
     "expo": {
       "version": "1.0.0",
       "android": {
         "package": "com.yourname.stockvaluation"
       }
     }
   }'
echo ""
read -p "Press Enter after updating app.json..."
echo ""

# Step 4: Build APK/AAB
echo "✅ STEP 4: Build Release AAB"
echo "---"
echo "Build Android App Bundle (AAB):"
echo ""
echo "  cd /Users/abiodunquadri/kivy/new\\ work\\ foler/stock-valuation-app/mobile"
echo "  eas build --platform android"
echo ""
echo "During build, EAS will ask:"
echo "  - Build type? → release"
echo "  - Sign with key? → yes"
echo "  - Use stored key? → no (first time)"
echo "  - Upload keystore? → yes"
echo ""
echo "EAS stores your keystore securely for future builds."
echo ""
read -p "Press Enter after build completes..."
echo ""

# Step 5: Create Play Console entry
echo "✅ STEP 5: Create App in Play Console"
echo "---"
echo "Go to https://play.google.com/console"
echo ""
echo "1. Click 'Create app'"
echo "2. App name: Stock Valuation"
echo "3. Default language: English"
echo "4. App category: Finance"
echo "5. Create"
echo ""
echo "You get:"
echo "  - Package name: com.yourname.stockvaluation"
echo "  - Bundle ID"
echo ""
read -p "Press Enter after creating app in Play Console..."
echo ""

# Step 6: Store listing
echo "✅ STEP 6: Fill Store Listing"
echo "---"
echo "In Play Console → Store listing:"
echo ""
echo "Short description (80 chars):"
echo "  'AI-powered stock valuation and market analysis'"
echo ""
echo "Full description (4000 chars):"
echo "  'Smart stock valuation tool for finding undervalued stocks."
echo "   - Real-time market analysis"
echo "   - Sector rotation tracking"
echo "   - Value investing recommendations'"
echo ""
echo "Category: Finance"
echo ""
echo "Required screenshots (minimum 2):"
echo "  - Home screen"
echo "  - Analysis screen"
echo "  - Market analysis"
echo "  - Watchlist"
echo ""
echo "Icon: 512x512 png"
echo "Featured image: 1024x500 png"
echo ""
read -p "Press Enter after filling store listing..."
echo ""

# Step 7: Privacy
echo "✅ STEP 7: App Privacy & Permissions"
echo "---"
echo "In Play Console → Store listing → App privacy:"
echo ""
echo "Privacy policy URL: your-website.com/privacy"
echo ""
echo "Permissions used:"
echo "  - Internet (for API calls)"
echo "  - INTERNET (Android manifest)"
echo ""
read -p "Press Enter after setting privacy..."
echo ""

# Step 8: Upload AAB
echo "✅ STEP 8: Upload AAB to Play Console"
echo "---"
echo "In Play Console → Releases → Create release:"
echo ""
echo "1. Select 'Production' or 'Internal testing'"
echo "2. Click 'Upload APK/AAB'"
echo "3. Select your .aab file (from EAS)"
echo "4. Review information"
echo "5. Click 'Save'"
echo ""
read -p "Press Enter after upload..."
echo ""

# Step 9: Testing
echo "✅ STEP 9: Internal Testing"
echo "---"
echo "Before going live, do internal testing:"
echo ""
echo "1. Go to Internal testing track"
echo "2. Upload your AAB"
echo "3. Add testers (email addresses)"
echo "4. Share internal testing link"
echo "5. Get feedback from 2-3 testers"
echo "6. Fix any issues"
echo ""
echo "Wait at least 24 hours for testing."
echo ""
read -p "Press Enter after internal testing..."
echo ""

# Step 10: Submit
echo "✅ STEP 10: Submit for Review"
echo "---"
echo "In Play Console → Production:"
echo ""
echo "1. Click 'Create release'"
echo "2. Upload your AAB"
echo "3. Review all details"
echo "4. Check content rating (click 'Add rating')"
echo "5. Check target audience"
echo "6. Click 'Review release'"
echo "7. Click 'Start rollout to Production'"
echo ""
echo "Google reviews your app (usually 1-2 hours)"
echo ""
read -p "Press Enter after submission..."
echo ""

# Final
echo "================================================================"
echo "✅ Google Play Store Deployment Complete!"
echo "================================================================"
echo ""
echo "What happens next:"
echo "  1. Google reviews your app (usually 1-2 hours)"
echo "  2. If approved: App goes live on Play Store"
echo "  3. Users can download from Google Play"
echo ""
echo "Your app is now on both iOS and Android stores! 🎉"
echo ""
