#!/bin/bash

# Stock Valuation App - Render.com Backend Deployment Script
# This script guides you through deploying the FastAPI backend to Render.com

echo "🚀 Stock Valuation App - Render.com Deployment Setup"
echo "================================================================"
echo ""

# Step 1: Check prerequisites
echo "✅ STEP 1: Prerequisites Check"
echo "---"
echo "Required:"
echo "  ✓ GitHub account (with repo pushed)"
echo "  ✓ Render.com account (free at render.com)"
echo "  ✓ API keys if using Alpha Vantage"
echo ""
read -p "Press Enter once you have these ready..."
echo ""

# Step 2: Push to GitHub
echo "✅ STEP 2: Push Backend to GitHub"
echo "---"
echo "Commands to run:"
echo ""
echo "cd /Users/abiodunquadri/kivy/new\ work\ foler/stock-valuation-app"
echo "git add ."
echo 'git commit -m "Deploy: Update backend for production"'
echo "git push origin main"
echo ""
read -p "Press Enter after pushing to GitHub..."
echo ""

# Step 3: Render setup
echo "✅ STEP 3: Create Render Web Service"
echo "---"
echo "Do this manually at render.com:"
echo ""
echo "1. Go to https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub account"
echo "4. Select your 'stock-valuation-app' repository"
echo "5. Fill in these settings:"
echo ""
echo "   Name: stock-valuation-api"
echo "   Environment: Python 3"
echo "   Region: Frankfurt (closest to you, or your preference)"
echo ""
echo "   Build Command:"
echo "   $ cd backend && pip install -r requirements.txt"
echo ""
echo "   Start Command:"
echo "   $ cd backend && python main.py"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
read -p "Press Enter after creating the service..."
echo ""

# Step 4: Environment variables
echo "✅ STEP 4: Set Environment Variables"
echo "---"
echo "In Render dashboard for your service:"
echo ""
echo "1. Go to Environment tab"
echo "2. Add these variables:"
echo ""
echo "   Key: PORT           Value: 8000"
echo "   Key: PYTHONUNBUFFERED  Value: 1"
echo ""
echo "   (If using Alpha Vantage:)"
echo "   Key: ALPHA_VANTAGE_API_KEY  Value: your_key_here"
echo ""
read -p "Press Enter after setting environment variables..."
echo ""

# Step 5: Deploy
echo "✅ STEP 5: Deploy!"
echo "---"
echo "Your backend should start deploying automatically."
echo ""
echo "Wait for the deployment to complete (2-5 minutes)."
echo "You'll see a green checkmark when it's live."
echo ""
echo "Your backend URL will be:"
echo "  https://stock-valuation-api.onrender.com"
echo ""
read -p "Press Enter once deployment is complete..."
echo ""

# Step 6: Test backend
echo "✅ STEP 6: Test Your Backend"
echo "---"
echo "Run this command to verify it's working:"
echo ""
echo "curl https://stock-valuation-api.onrender.com/docs"
echo ""
echo "You should see the Swagger API documentation."
echo ""
read -p "Press Enter to continue..."
echo ""

# Step 7: Update mobile app
echo "✅ STEP 7: Update Mobile App"
echo "---"
echo "Update your mobile backend URL:"
echo ""
echo "Edit: /Users/abiodunquadri/kivy/new\\ work\\ foler/stock-valuation-app/mobile/.env"
echo ""
echo "Change:"
echo "  EXPO_PUBLIC_API_URL=http://localhost:8000"
echo ""
echo "To:"
echo "  EXPO_PUBLIC_API_URL=https://stock-valuation-api.onrender.com"
echo ""
read -p "Press Enter after updating .env..."
echo ""

# Step 8: Redeploy mobile
echo "✅ STEP 8: Reload Mobile App"
echo "---"
echo "In your Expo terminal, press 'r' to reload the app"
echo ""
echo "The app should now connect to your production backend!"
echo ""
read -p "Press Enter after testing..."
echo ""

# Final summary
echo "================================================================"
echo "🎉 DEPLOYMENT COMPLETE!"
echo "================================================================"
echo ""
echo "✅ Backend URL: https://stock-valuation-api.onrender.com"
echo "✅ Mobile connected to production backend"
echo ""
echo "Next steps:"
echo "  1. Test all features in the mobile app"
echo "  2. (Optional) Deploy to App Store / Play Store"
echo "  3. (Optional) Set up custom domain"
echo ""
echo "Troubleshooting:"
echo "  • Backend not starting? Check Render logs in dashboard"
echo "  • Mobile app shows API error? Check .env URL is correct"
echo "  • Cold start (slow first load)? Normal on free tier"
echo ""
